### ISSUE TITLE
SerialName option

### ISSUE THREAD

**Issue by yannickpulver** [rubenquadros/codespector#3]
Hi! Thanks for the plugin!

It would be cool if it could add `@SerialName` annotation (`kotlinx.serialization.SerialName`) instead of `SerializedName` from GSON.

**Comment by rubenquadros** [comment]
Hi, glad you liked it!
This is already in the works. If you want to track the updates you can check this branch:
https://github.com/rubenquadros/codespector/tree/moshi-kotlinx-support
